'use strict';

const http = require('http'),
      path = require('path');

const express = require('express'),
      flaschenpost = require('flaschenpost'),
      processenv = require('processenv');

const loggerSystem = flaschenpost.getLogger();

const DocumentationApi = require('../../apis/Documentation'),
      DocumentationWebApp = require('../../webapps/Documentation');

(async () => {
  try {
    const app = express();

    const contentDirectory = processenv('CONTENT_DIRECTORY') || path.join(__dirname, '..', '..', 'documentation'),
          port = processenv('PORT') || 3000,
          runtimeVersions = processenv('RUNTIME_VERSIONS') || require('../../documentation/versions-autogenerated.json');

    const documentationApi = new DocumentationApi.Http();

    await documentationApi.initialize({
      contentDirectory,
      corsOrigin: '*',
      nodeEnv: processenv('NODE_ENV') || 'development',
      runtimeVersions
    });

    const documentationWebApp = new DocumentationWebApp();

    await documentationWebApp.initialize({
      contentDirectory,
      nodeEnv: processenv('NODE_ENV') || 'development'
    });

    app.use('/api', documentationApi.api);
    app.use(documentationWebApp.api);

    const server = http.createServer(app);

    server.listen(port, err => {
      if (err) {
        throw err;
      }

      loggerSystem.info(`Website server listening on port ${port}.`);
    });
  } catch (ex) {
    loggerSystem.fatal('An unexpected error occured.', { err: ex });

    /* eslint-disable no-process-exit */
    process.exit(1);
    /* eslint-enable no-process-exit */
  }
})();
